apiVersion: "kubedirector.hpe.com/v1beta1"
kind: "KubeDirectorCluster"
metadata:
  name: "ngc-tensorflow-cluster"
spec:
  app: ngc-tensorflow
  roles:
  - id: tensorflow
    members: 1
    resources:
      requests:
        memory: "4Gi"
        cpu: "2"
        nvidia.com/gpu: "1" 
      limits:
        memory: "4Gi"
        cpu: "2"
        nvidia.com/gpu: "1" 
